### ISSUE TITLE
Cannot open the file stored in local

### ISSUE THREAD

**Issue by fortunehan** [dgmjs/dgmjs#141] opened 2024-06-18 11:17 UTC
Hi,
I'm getting an "something went wrong" error when trying to open a file saved locally. Even after adding a simple rectangle and saving it locally, I can't open it. 
I created a diagram with 4 pages, but I can't access it now. 

Apple M1 Max MacBook Pro, 13.6.6 (22G630)

**Comment by niklauslee** [comment] 2024-06-18 12:31
@fortunehan I can't reproduce the issue, so could you provide your `.dgm` file?

**Comment by fortunehan** [comment] 2024-06-18 22:37
[Untitled.dgm.zip](https://github.com/user-attachments/files/15893299/Untitled.dgm.zip)
I cannot upload the .dgm directly, please unzip the attachment.

below is the error in the console
<img width="584" alt="image" src="https://github.com/dgmjs/dgmjs/assets/9983619/1d8a5527-e5b6-4ff1-bd3a-e579ac9bec2b">

**Comment by niklauslee** [comment] 2024-06-19 00:44
Thank you for providing the file. There was an issue with the connection points in the Connector part, this is now fixed, please try again in dgm.sh (maybe your Connector needs a little polish)

**Closed by niklauslee** 2024-06-19 00:44 UTC
Labels: bug
